services:
  file-server:
    container_name: file-server
    image: tuannnh/file-server:latest
    ports:
      - 11119:8501
    volumes:
      - /DATA/AppData/file-server/data:/app/data
    restart: unless-stopped
    network_mode: bridge