name: ebook-crawler
services:
  ebook-crawler:
    image: your-registry/ebook-crawler:latest
    container_name: ebook-crawler
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/ebook-crawler:/data/
    ports:
      - HOST_PORT:CONTAINER_PORT
    restart: unless-stopped
    network_mode: bridge
