name: qbittorrent
services:
  qbittorrent:
    container_name: qbittorrent
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Ho_Chi_Minh
      - UMASK=002
    hostname: qbittorrent
    image: hotio/qbittorrent:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/icon.png
    ports:
      - "11124:8080"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/qbittorrent/config:/config
      - /server_data/torrents/:/DATA/torrents
      - /server_data/media/:/DATA/media
    network_mode: bridge
    privileged: false
