name: qbittorrent
services:
  qbittorrent:
    container_name: qbittorrent
    environment:
      - PGID=0
      - PUID=0
      - TZ=Asia/Ho_Chi_Minh
      - UMASK=002
    hostname: qbittorrent
    image: hotio/qbittorrent:latest
    ports:
      - "11124:8080"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/qbittorrent/config:/config
      - /srv/data/backups/pc-torrents/torent-file/:/DATA/torrents
      - /srv/data/backups/pc-torrents/media:/DATA/media
    network_mode: bridge
    privileged: false
