name: localstack
services:
  localstack:
    image: localstack/localstack-pro
    container_name: localstack
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/localstack:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "44443:44443"
    restart: unless-stopped