name: postgresql
services:
  postgresql:
    cpu_shares: 90
    command: []
    container_name: postgresql
    deploy:
      resources:
        limits:
          memory: 32013M
        reservations:
          memory: "2147483648"
    hostname: postgresql
    image: postgres:15.3
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PostgreSQL/icon.png
    ports:
      - target: 5432
        published: "5432"
        protocol: tcp
    restart: unless-stopped
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - type: bind
        source: /DATA/AppData/postgresql/data
        target: /var/lib/postgresql/data
    privileged: false
    network_mode: bridge