services:
  meshcentral:
    env_file:
      - stack.env
    container_name: meshcentral
    restart: unless-stopped # always restart the container unless you stop it
    image: ghcr.io/ylianst/meshcentral:master # 1.1.27 is a version number OR use master for the master branch of bug fixes
    ports:
      - 11129:80 # HTTP
      - 11130:443
    volumes:
      - /DATA/AppData/meshcentral/data:/opt/meshcentral/meshcentral-data # config.json and other important files live here
      - /DATA/AppData/meshcentral/user_files:/opt/meshcentral/meshcentral-files # where file uploads for users live
      - /DATA/AppData/meshcentral/backup:/opt/meshcentral/meshcentral-backups # location for the meshcentral backups - this should be mounted to an external storage
      - /DATA/AppData/meshcentral/web:/opt/meshcentral/meshcentral-web # location for site customization files