name: apprise
services:
  apprise:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/apprise/config:/config
      - /DATA/AppData/apprise/attachments:/attachments
    ports:
      - "11140:8000"
    restart: unless-stopped
    network_mode: bridge