x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: [ 'n8n' ]
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: [ 'n8n' ]
  restart: unless-stopped
  ports:
    - 11138:11434
  volumes:
    - /DATA/AppData/n8n/ollama_storage:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: [ 'n8n' ]
  container_name: ollama-pull-llama
  volumes:
    - /DATA/AppData/n8n/ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    - "sleep 3; OLLAMA_HOST=ollama:11434 ollama pull llama3.2"

services:
  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
    volumes:
      - /DATA/AppData/n8n/backup:/backup

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 11137:5678
    volumes:
      - /DATA/AppData/n8n/storage:/home/node/.n8n
      - /DATA/AppData/n8n/backup:/backup
      - /DATA/AppData/n8n/shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks: [ 'n8n' ]
    restart: unless-stopped
    ports:
      - 11139:6333
    volumes:
      - /DATA/AppData/n8n/qdrant_storage:/qdrant/storage

  ollama-cpu:
    profiles: [ "cpu" ]
    <<: *service-ollama


  ollama-pull-llama-cpu:
    profiles: [ "cpu" ]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

networks:
  n8n:
    driver: bridge
