services:

  n8n:
    image: n8nio/n8n:${N8N_IMAGE_VERSION:-latest}
    env_file:
      - stack.env
    networks: [ 'n8n' ]
    container_name: n8n
    user: "${UID}:${GID}"
    restart: unless-stopped
    ports:
      - 11137:5678
    volumes:
      - /DATA/AppData/n8n/storage:/home/node/.n8n
      - /DATA/AppData/n8n/backup:/backup
      - /DATA/AppData/n8n/shared:/data/shared

  task-runners:
    image: n8nio/runners:${N8N_IMAGE_VERSION:-latest}
    container_name: n8n-runners
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/n8n/runners/n8n-task-runners.json:/etc/n8n-task-runners.json
    depends_on:
      - n8n
    networks: [ 'n8n' ]    

networks:
  n8n:
    name: n8n
    driver: bridge
