services:

  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_IMAGE_VERSION:-latest}
    env_file:
      - stack.env
    container_name: n8n
    user: "${UID}:${GID}"
    restart: unless-stopped
    ports:
      - 11137:5678
    volumes:
      - /DATA/AppData/n8n/storage:/home/node/.n8n
      - /DATA/AppData/n8n/backup:/backup
      - /DATA/AppData/n8n/shared:/data/shared
    network_mode: bridge
