FROM ghcr.io/tuannnh/home-stacks/custom-n8n-runners:latest
USER root
# RUN cd /opt/runners/task-runner-javascript && pnpm add moment uuid
RUN cd /opt/runners/task-runner-python && uv pip install numpy pandas beautifulsoup4 requests pymongo
COPY n8n-task-runners.json /etc/n8n-task-runners.json
USER runner