services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
    ports:
      - 11111:3000
    volumes:
      - /DATA/AppData/homepage/config:/app/config # Make sure your local config directory exists
      - /DATA/AppData/homepage/images:/app/public/images
      - /DATA/AppData/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # optional, for docker integrations
    restart: unless-stopped
    network_mode: bridge