name: trilium
services:
  trilium:
    cpu_shares: 90
    command: []
    container_name: trilium
    deploy:
      resources:
        limits:
          memory: 32013M
        reservations:
          memory: "268435456"
    hostname: trilium
    image: zadam/trilium:0.63-latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Trilium/icon.png
    ports:
      - target: 8080
        published: "11132"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/trilium
        target: /home/node/trilium-data
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
