name: trilium
services:
  trilium:
    image: triliumnext/trilium:latest
    container_name: trilium
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/trilium:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 11126:8080
    restart: unless-stopped
    network_mode: bridge
