name: mongodb
services:
  mongo:
    cpu_shares: 90
    command: []
    container_name: mongo
    deploy:
      resources:
        limits:
          memory: 32013M
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Ho_Chi_Minh
    hostname: mongo
    image: mongo:latest
    ports:
      - target: 27017
        published: "27017"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/mongo/data/configdb
        target: /data/configdb
      - type: bind
        source: /DATA/AppData/mongo/data/db
        target: /data/db
    privileged: false
    network_mode: bridge
