name: leetbot
services:
  leetbot:
    image: tuannnh/leetbot:latest
    container_name: leetbot
    restart: unless-stopped
    ports:
      - 11122:8000
    environment:
      - OPEN_API_KEY=<OPEN_API_KEY>
    network_mode: bridge
