services:
  infisical:
    container_name: infisical-backend
    restart: unless-stopped
    env_file: stack.env
    depends_on:
      redis:
        condition: service_started
    image: infisical/infisical:latest-postgres
    pull_policy: always
    ports:
      - 11116:8080
    environment:
      - NODE_ENV=production
    networks:
      - infisical

  redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: stack.env
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - infisical
    volumes:
      - /DATA/AppData/infisical/redis/redis_data:/data

networks:
  infisical:
    name: infisical
    driver: bridge

