services:
  db-migration:
    container_name: infisical-db-migration
    image: infisical/infisical:latest-postgres
    command: npm run migration:latest
    pull_policy: always
    networks:
      - infisical

  infisical:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    image: infisical/infisical:latest-postgres
    pull_policy: always
    ports:
      - 11116:8080
    environment:
      - NODE_ENV=production
    networks:
      - infisical

  redis:
    image: redis
    container_name: infisical-dev-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - infisical
    volumes:
      - /DATA/AppData/redis/redis_data:/data

networks:
  infisical: