name: rustdesk
services:
  rustdesk-hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    command: hbbs
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/rustdesk:/root
    ports:
      - 21114:21114
      - 21115:21115
      - 21116:21116/udp
      - 21116:21116/tcp
      - 21118:21118

    depends_on:
      - rustdesk-hbbr
    restart: unless-stopped
    network_mode: 
      - rustdesk

  rustdesk-hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/rustdesk:/root
    ports:
      - 21117:21117
      - 21119:21119
    restart: unless-stopped
    network_mode: 
      - rustdesk

networks:
  rustdesk:
    name: rustdesk
    driver: bridge