name: stack_name
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    env_file:
      - stack.env
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    network_mode: host