name: tuaniverse_chat
services:
  tuaniverse_chat:
    container_name: tuaniverse-chatbot-ui
    deploy:
      resources:
        limits:
          memory: "4294967296"
    environment:
      OPENAI_API_KEY: <OPEN_API_KEY>
    hostname: chatbot-ui
    image: tuannnh/chatbot-ui:latest
    labels:
      icon: https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Icone_wikipedia_bureaucrat_bot.svg/120px-Icone_wikipedia_bureaucrat_bot.svg.png
    ports:
      - 11117:3000
    restart: unless-stopped