name: jellyfin
services:
  jellyfin:
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Ho_Chi_Minh
    hostname: jellyfin
    image: linuxserver/jellyfin:latest
    ports:
      - "11121:8096"
      - "8921:8920"
      - "7359:7359"
      - "1901:1900"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/jellyfin/config:/config
      - /server_data/syncthing:/Media/Syncthing
      - /server_data/torrents:/Media/Torrents
      - /opt/vc/lib:/opt/vc/lib
    network_mode: bridge
