name: jellyfin
services:
  jellyfin:
    container_name: jellyfin
    deploy:
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: "268435456"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Ho_Chi_Minh
    hostname: jellyfin
    image: linuxserver/jellyfin:latest
    ports:
      - target: 8096
        published: "11121"
        protocol: tcp
      - target: 8920
        published: "8921"
        protocol: tcp
      - target: 7359
        published: "7359"
        protocol: tcp
      - target: 1900
        published: "1901"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin/config
        target: /config
      - type: bind
        source: /server_data/syncthing
        target: /Media/Syncthing
      - type: bind
        source: /opt/vc/lib
        target: /opt/vc/lib
      - type: bind
        source: /server_data/torrents
        target: /Media/Torrents
    network_mode: bridge
    privileged: false
