name: jellyfin
services:
  jellyfin:
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PGID=0
      - PUID=0
      - TZ=Asia/Ho_Chi_Minh
    hostname: jellyfin
    image: linuxserver/jellyfin:latest
    ports:
      - "11121:8096"
      - "8921:8920"
      - "7359:7359"
      - "1901:1900"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/jellyfin/config:/config
      - /srv/data/backups/syncthing:/media/syncthing
      - /srv/data/backups/pc-torrents:/media/torrents
      - /opt/vc/lib:/opt/vc/lib
    network_mode: bridge
