name: portainer
services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ee:lts
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "11112:8000"
      - "11113:9000"
      - "11114:9443"
    environment:
      - TRUSTED_ORIGINS=portainer.hungtuan.me
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/portainer
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    network_mode: bridge