name: market
services:
  market:
    image: tuannnh/market:latest
    container_name: market
    restart: unless-stopped
    ports:
      - 11123:8501
    network_mode: bridge
    env_file:
      - stack.env