name: affine
services:
  affine:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_server
    ports:
      - 11116:3010
    env_file:
      - stack.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
      indexer:
        condition: service_healthy
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=${DATABASE_URL}
      - AFFINE_INDEXER_ENABLED=true
      - AFFINE_INDEXER_SEARCH_ENDPOINT=http://indexer:9308
    restart: unless-stopped
    networks:
      - affine_network

  affine_migration:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    env_file:
      - stack.env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=${DATABASE_URL}
      - AFFINE_INDEXER_ENABLED=true
      - AFFINE_INDEXER_SEARCH_ENDPOINT=http://indexer:9308
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - affine_network

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - affine_network

  indexer:
      image: manticoresearch/manticore:${MANTICORE_VERSION:-10.1.0}
      container_name: affine_indexer
      env_file:
        - stack.env
      volumes:
        - ${MANTICORE_DATA_LOCATION}:/var/lib/manticore
      ulimits:
        nproc: 65535
        nofile:
          soft: 65535
          hard: 65535
        memlock:
          soft: -1
          hard: -1
      healthcheck:
        test:
          ['CMD', 'wget', '-O-', 'http://127.0.0.1:9308']
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped
      networks:
        - affine_network

networks:
  affine_network:
    name: affine_network
    driver: bridge