name: metube
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/metube:/downloads
    ports:
      - "11146:8081"
    restart: unless-stopped
    network_mode: bridge