name: syncthing
services:
  syncthing:
    cpu_shares: 90
    container_name: syncthing
    deploy:
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: "268435456"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Ho_Chi_Minh
    hostname: syncthing
    image: linuxserver/syncthing:1.27.6
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Syncthing/icon.png
    ports:
      - target: 8384
        published: "11125"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: udp
      - target: 21027
        published: "21027"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/syncthing/config
        target: /config
      - type: bind
        source: /srv/data/backups/syncthing
        target: /DATA
    network_mode: bridge
    privileged: false
