services:
  api:
    container_name: bipal
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - rag_api
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: "${UID}:${GID}"
    networks:
      - bipal
    env_file:
      - stack.env
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=${MONGO_URI:-mongodb://10.1.1.99:27017/librechat}
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      #      - /DATA/AppData/bipal/librechat.yaml:/app/librechat.yaml
      - /DATA/AppData/bipal/images:/app/client/public/images
      - /DATA/AppData/bipal/logs:/app/api/logs

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    networks:
      - bipal
    #    user: "${UID}:${GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - /DATA/AppData/bipal/meili_data:/meili_data
    env_file:
      - stack.env

  vectordb:
    container_name: vectordb
    image: ankane/pgvector:latest
    restart: always
    volumes:
      - /DATA/AppData/bipal/vectordb:/var/lib/postgresql/data
    networks:
      - bipal
    env_file:
      - stack.env

  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - stack.env
    networks:
      - bipal

networks:
  default:
    name: bipal
    driver: bridge